/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aizhunimei_rtmpplayer_nativeutil_NativeUtil */

#ifndef _Included_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
#define _Included_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
 * Method:    naInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil_naInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
 * Method:    naGetVideoRes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil_naGetVideoRes
  (JNIEnv *, jclass);

/*
 * Class:     com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
 * Method:    naSetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil_naSetSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
 * Method:    naSetup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil_naSetup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
 * Method:    naPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil_naPlay
  (JNIEnv *, jclass);

/*
 * Class:     com_aizhunimei_rtmpplayer_nativeutil_NativeUtil
 * Method:    naStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aizhunimei_rtmpplayer_nativeutil_NativeUtil_naStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
